channels:
  - defaults
  - conda-forge
  - astra-toolbox
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - tomopy
  - astra-toolbox
  - dxchange
  - svmbir
  - scikit-image
  - jupyterlab
  - ipympl
  - ipyfilechooser